# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Andrew Raychawdhuri"
title_separator          : "-"
name                     : &name "Andrew Raychawdhuri"
description              : &description "personal description"
url                      : https://andrewraychawdhuri.github.io
baseurl                  : ""
repository               : "andrewraychawdhuri/andrewraychawdhuri.github.io"

# Author
author:
  avatar           : "prof.png"
  name             : "Andrew Raychawdhuri"
  bio              : ""
  location         : "College Park, MD"
  employer         : "University of Maryland"
  email            : "andrew.raychawdhuri@gmail.com"
  github           : "andrewraychawdhuri"
  linkedin         : andrew-raychawdhuri-3a2318182/

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : false
atom_feed:
  hide                   : false

# SEO Related
google_site_verification : "paVN48jgehISXflQdzua-zNr12zicUqsHnKdeszLqTM"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - vendor
keep_files:
  - .git
  - .svn

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development 
