# Basic Site Settings
title: "Andrew Raychawdhuri"
name: "Andrew Raychawdhuri"
description: "personal description"
url: "https://andrewraychawdhuri.github.io"
baseurl: "" # leave empty for user.github.io sites
repository: "andrewraychawdhuri/andrewraychawdhuri.github.io"
locale: "en-US"

# Author Info
author:
  avatar: "prof.png"
  name: "Andrew Raychawdhuri"
  location: "College Park, MD"
  employer: "University of Maryland"
  email: "andrew.raychawdhuri@gmail.com"
  github: "andrewraychawdhuri"
  linkedin: "andrew-raychawdhuri-3a2318182/"

# Collections (only research is needed)
collections:
  research:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # Pages in _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # Individual research papers in _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:title/
timezone: Etc/UTC
